language: objective-c
osx_image: xcode9.4
dist: trusty

addons:
  sonarcloud:
    organization: "scior_github"
    token:
      secure: "qUWqESb69O+3YbyLeoZjNTZh9eggUjiVYm5Mn/8GPRFfm3yIe7YQzUAr3bejyd5jOiJTGFitl+iBCEhz54Cet0F6+jJGdjBR3rjbrMaMqwdpuRJkT31dQNg7zwD8DSiE8d3xhrCMNYG/aIuAU0xqAp8BQU08ONZKO6U+bEG9RFl9pF92GFkRGHXYc7T0HeW9LH2LnRzHLQb/SqBd22Z+mi1BFtwIsEZGY0tDGfJ+XFrkBTdG4SnwZlt3zZOv9DBleOiqAV4jpVQKduOZI/kJgrQdNK2etrYvAf4Q4hFe4GVfcV09j/qQUs0EW/G2EfvnCUrVXpExDPHFcfuetuH7OWuzze869W0DQ8gPI0rkXGBr1cEWAJUke129YhWyzlrmesj81HgzWUppmJ7MfN2GNRp5SgN8vsfWvDPH8WnSF+CQd/vcUUSotjebVfQLlkv5oRGXO4Wub8tRPM+UinyoV1+BADCm1Oax+YMECJRep916EuySOVg0umxBcF7bD15g4AawWZd7oxWKPZ3UjlaVwbo1IPxuVWfWrSJgbo68+90vsuMlyRMm0qtbz5pdkMwTFtCqdnRknm2Tpt4+vav4b65TB6lgwFgY9hRVbrdqmDXc6yg1YiCbNLe8zyx+tx1Z75DKxdcc+LK9Anfa8buE/bDfvqI0c9dJ/lMJjOlvWgc="

script: 
  - fastlane test
  - sonar-scanner

branches:
  only:
    - master
